services:
  # Емулятор сервера авторизації
  auth-mock:
    image: wiremock/wiremock:latest
    container_name: cosmo-auth-mock
    ports:
      - "8081:8080" # На хості буде 8081, всередині контейнера 8080
    volumes:
      - ./wiremock:/home/wiremock
    command: --verbose --global-response-templating

  # База даних
  postgres:
    image: postgres:15-alpine
    container_name: cosmo-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: cosmocats
      POSTGRES_USER: cosmo
      POSTGRES_PASSWORD: cosmo