server:
  port: 8080

spring:
  application:
    name: lab3-cosmocats-db

  datasource:
    url: jdbc:postgresql://localhost:5432/cosmocats
    username: cosmo
    password: cosmo
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

feature:
  cosmoCats:
    enabled: true      # ⬅ ВАЖЛИВО! Вмикає фічу
  kittyProducts:
    enabled: false     # можна лишити як є

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
app:
  security:
    api-key:
      header-name: X-API-KEY
      secret: cosmo-secret-key-123
      role: ROLE_ADMIN
    jwt:
      secret: my-very-secret-key-for-tests-only-must-be-long-enough
      algorithm: HS256

